# This config is for testing PredRNN++ on climate data
# WORK IN PROGRESS

output_dir: $SCRATCH/nesap-stl/predrnn3d-climate/results

trainer: auto_regressive

data:
    name: climate
    data_file: /global/cfs/cdirs/m1759/sfarrell/nesap-stl/data/climate.npz
    patch_size: 4
    n_train: 8192
    n_valid: 2048
    seq_len: 16
    batch_size: 4

model:
    name: predrnn_pp
    num_hidden: [8, 16, 32, 16]
    #num_hidden: [128, 64, 64, 64, 16]

loss:
    name: MSELoss

optimizer:
    name: Adam
    lr: 0.001

train:
    n_epochs: 32
