# This config is for testing PredRNN++ on fMRI data

output_dir: $SCRATCH/nesap-stl/prnn3d-fmri/results

trainer: auto_regressive

data:
    name: fmri
    data_dir: /global/cscratch1/sd/sswwhan/abcd-fmriprep-rs-npz/
    target_filepath: /global/homes/s/sswwhan/demo.total.csv
    target_label: sex
    n_train: 8
    n_valid: 8
    n_test: 8
    time_frames: 32
    # patch_size: 2
    batch_size: 1

model:
    name: predrnn_pp
    num_dims: 3
    num_hidden: [8, 8, 8, 8]

loss:
    name: MSELoss

optimizer:
    name: Adam
    lr: 0.001

train:
    n_epochs: 2
